/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Schema {
  /**
   * sam with a name
   */
  name?: string;
  /**
   * path to create the enum
   */
  path?: string;
  /**
   * Specifies if a spec file is generated
   */
  spec?: boolean;
  /**
   * Specifies the type of the thing
   */
  type?: string;
  [k: string]: any;
}
